Repository Lussebullen/DD2480_DECIDE, pull requests merged in 2024-02, with the labels that each got.

#56 feat/ Implemented LIC4 & unit test
  decide/src/main/java/group17/App.java
  decide/src/main/java/group17/LicAnalyzer.java
  decide/src/test/java/group17/LicAnalyzerTest.java
Labels: enhancement

#89 fix/ Fix bug addressed in issue 88
  decide/src/main/java/group17/App.java
Labels: bug

#96 Issue/57 Update README
  README.md
Labels: documentation
